import os
from typing import Dict, Iterable, Tuple

import matplotlib.pyplot as plt
import pandas as pd


DEFAULT_MODELS = ["uniform", "biased", "leakage"]


def ensure_dir(path: str) -> None:
    os.makedirs(path, exist_ok=True)


def load_frequency_distribution(csv_path: str) -> pd.DataFrame:
    """
    Load a frequency CSV produced by the main pipeline.

    Expected columns:
        pin, count, probability
    """
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"Missing frequency file: {csv_path}")

    df = pd.read_csv(csv_path, dtype={"pin": str})
    df["pin"] = df["pin"].astype(str).str.zfill(6)

    required_columns = {"pin", "probability"}
    missing = required_columns - set(df.columns)

    if missing:
        raise ValueError(
            f"{csv_path} is missing required columns: {missing}. "
            "Expected at least: pin, probability"
        )

    df["probability"] = df["probability"].astype(float)
    df = df.sort_values(by="probability", ascending=False).reset_index(drop=True)

    return df


def compute_blacklist_defense(
    freq_df: pd.DataFrame,
    blacklist_sizes: Iterable[int] = (10, 50, 100, 500),
    evaluation_k: int = 10
) -> pd.DataFrame:
    """
    Weak PIN blacklisting defense.

    The system blocks the top-N most frequent PINs.
    After removing them, the remaining probability distribution is normalized.
    Then Top-k success is recomputed on the filtered distribution.
    """
    rows = []

    original_topk_success = freq_df.head(evaluation_k)["probability"].sum()

    for n in blacklist_sizes:
        filtered = freq_df.iloc[n:].copy()

        if filtered.empty:
            continue

        remaining_mass = filtered["probability"].sum()

        if remaining_mass <= 0:
            continue

        filtered["normalized_probability"] = (
            filtered["probability"] / remaining_mass
        )

        new_topk_success = (
            filtered.head(evaluation_k)["normalized_probability"].sum()
        )

        absolute_reduction = original_topk_success - new_topk_success

        relative_reduction_percent = (
            absolute_reduction / original_topk_success * 100
            if original_topk_success > 0
            else 0
        )

        rows.append({
            "defense": "weak_pin_blacklisting",
            "blacklist_size": n,
            "evaluation_k": evaluation_k,
            "original_topk_success": original_topk_success,
            "new_topk_success": new_topk_success,
            "absolute_reduction": absolute_reduction,
            "relative_reduction_percent": relative_reduction_percent,
        })

    return pd.DataFrame(rows)


def plot_blacklist_defense(
    blacklist_results: pd.DataFrame,
    output_path: str
) -> None:
    """
    Plot Top-10 success rate after weak PIN blacklisting.
    """
    plt.figure(figsize=(9, 5))

    for model in blacklist_results["model"].unique():
        subset = blacklist_results[blacklist_results["model"] == model]

        plt.plot(
            subset["blacklist_size"],
            subset["new_topk_success"],
            marker="o",
            label=model
        )

    plt.xlabel("Number of Most Frequent PINs Blacklisted")
    plt.ylabel("New Top-10 Attack Success Rate")
    plt.title("Defense Study: Weak PIN Blacklisting")
    plt.xticks([10, 50, 100, 500])
    plt.grid(True, alpha=0.3)
    plt.legend()
    plt.tight_layout()

    plt.savefig(output_path, dpi=300)
    plt.close()


def run_defense_study(
    data_dir: str = "data",
    results_dir: str = "results",
    figures_dir: str = "results/figures",
    models: Iterable[str] = DEFAULT_MODELS,
    blacklist_sizes: Tuple[int, ...] = (10, 50, 100, 500),
    evaluation_k: int = 10
) -> Dict[str, pd.DataFrame]:
    """
    Run the weak PIN blacklisting defense study.

    This function uses frequency files generated by the main pipeline:
        results/frequency_uniform.csv
        results/frequency_biased.csv
        results/frequency_leakage.csv

    Outputs:
        results/defense_blacklist.csv
        results/figures/defense_blacklist.png
    """
    ensure_dir(results_dir)
    ensure_dir(figures_dir)

    all_blacklist_results = []

    for model in models:
        frequency_path = os.path.join(results_dir, f"frequency_{model}.csv")

        print(f"[Defense] Loading distribution: {frequency_path}")
        freq_df = load_frequency_distribution(frequency_path)

        blacklist_df = compute_blacklist_defense(
            freq_df=freq_df,
            blacklist_sizes=blacklist_sizes,
            evaluation_k=evaluation_k
        )

        blacklist_df.insert(0, "model", model)
        all_blacklist_results.append(blacklist_df)

    if not all_blacklist_results:
        raise RuntimeError("No weak PIN blacklisting results were generated.")

    blacklist_results = pd.concat(all_blacklist_results, ignore_index=True)

    blacklist_csv = os.path.join(results_dir, "defense_blacklist.csv")
    blacklist_results.to_csv(blacklist_csv, index=False)

    blacklist_plot = os.path.join(figures_dir, "defense_blacklist.png")
    plot_blacklist_defense(blacklist_results, blacklist_plot)

    print("[OK] Weak PIN blacklisting defense study completed.")
    print(f"[OK] Saved CSV: {blacklist_csv}")
    print(f"[OK] Saved plot: {blacklist_plot}")

    return {
        "blacklist": blacklist_results
    }


if __name__ == "__main__":
    run_defense_study()